import { ApiTags, createRoute } from "../lib/route-wrapper";
import {
  AddonsListResponseSchema,
  AddonPathParamsSchema,
  AddonQueryParamsSchema,
  AddonResponseSchema,
  CreateAddonRequestSchema,
  UpdateAddonRequestSchema,
  AddonConfigurationsListResponseSchema,
  AddonConfigurationPathParamsSchema,
  AddonConfigurationQueryParamsSchema,
  UpdateAddonConfigurationPathParamsSchema,
  UpdateAddonConfigurationRequestSchema,
  UpdateAddonConfigurationResponseSchema,
  DeleteAddonConfigurationResponseSchema,
} from "../schemas";

export const AddonRouteDefinitions = {
  getAddons: createRoute({
    method: "get",
    path: "/addons",
    summary: "Get all addons",
    description:
      "Retrieve a list of addons with optional filters and pagination",
    tags: [ApiTags.ADDONS],
    successSchema: AddonsListResponseSchema,
    successDescription: "Addons retrieved successfully",
    querySchema: AddonQueryParamsSchema,
    includeBadRequest: true,
  }),
  getAddonById: createRoute({
    method: "get",
    path: "/addons/{id}",
    summary: "Get addon by ID",
    description: "Retrieve a specific addon by its ID",
    tags: [ApiTags.ADDONS],
    successSchema: AddonResponseSchema,
    successDescription: "Addon retrieved successfully",
    paramsSchema: AddonPathParamsSchema,
    includeNotFound: true,
  }),
  createAddon: createRoute({
    method: "post",
    path: "/addons",
    summary: "Create addon",
    description: "Create a new addon",
    tags: [ApiTags.ADDONS],
    successSchema: AddonResponseSchema,
    successDescription: "Addon created successfully",
    requestSchema: CreateAddonRequestSchema,
    includeBadRequest: true,
    includeConflict: true,
  }),

  updateAddon: createRoute({
    method: "put",
    path: "/addons/{id}",
    summary: "Update addon",
    description: "Update an existing addon",
    tags: [ApiTags.ADDONS],
    successSchema: AddonResponseSchema,
    successDescription: "Addon updated successfully",
    paramsSchema: AddonPathParamsSchema,
    requestSchema: UpdateAddonRequestSchema,
    includeBadRequest: true,
    includeNotFound: true,
    includeConflict: true,
  }),

  deleteAddon: createRoute({
    method: "delete",
    path: "/addons/{id}",
    summary: "Delete addon",
    description: "Delete an existing addon",
    tags: [ApiTags.ADDONS],
    successSchema: AddonResponseSchema,
    successDescription: "Addon deleted successfully",
    paramsSchema: AddonPathParamsSchema,
    includeNotFound: true,
  }),
  getAddonConfigurations: createRoute({
    method: "get",
    path: "/addons/{id}/configurations",
    summary: "Get addon configurations",
    description: "Retrieve configurations for a specific addon",
    tags: [ApiTags.ADDONS],
    successSchema: AddonConfigurationsListResponseSchema,
    successDescription: "Addon configurations retrieved successfully",
    paramsSchema: AddonConfigurationPathParamsSchema,
    querySchema: AddonConfigurationQueryParamsSchema,
    includeNotFound: true,
  }),
  updateAddonConfiguration: createRoute({
    method: "put",
    path: "/addons/configurations/{id}",
    summary: "Update addon configuration",
    description: "Update a specific addon configuration",
    tags: [ApiTags.ADDONS],
    successSchema: UpdateAddonConfigurationResponseSchema,
    successDescription: "Addon configuration updated successfully",
    paramsSchema: UpdateAddonConfigurationPathParamsSchema,
    requestSchema: UpdateAddonConfigurationRequestSchema,
    includeNotFound: true,
    includeBadRequest: true,
  }),
  deleteAddonConfiguration: createRoute({
    method: "delete",
    path: "/addons/configurations/{id}",
    summary: "Delete addon configuration",
    description: "Delete a specific addon configuration",
    tags: [ApiTags.ADDONS],
    successSchema: DeleteAddonConfigurationResponseSchema,
    successDescription: "Addon configuration deleted successfully",
    paramsSchema: UpdateAddonConfigurationPathParamsSchema,
    includeNotFound: true,
  }),
};
