import { ApiTags, createAuthenticatedRoute } from "../lib/openapi";
import {
  TaxFeesListResponseSchema,
  TaxFeePathParamsSchema,
  TaxFeeQueryParamsSchema,
  TaxFeeResponseSchema,
  CreateTaxFeeRequestSchema,
  UpdateTaxFeeRequestSchema,
} from "../schemas";

export const TaxFeeRouteDefinitions = {
  getTaxFees: createAuthenticatedRoute({
    method: "get",
    path: "/tax-fees",
    summary: "Get tax/fee rules",
    description: "Retrieve tax/fee rules with filters and pagination",
    tags: [ApiTags.TAXES],
    successSchema: TaxFeesListResponseSchema,
    successDescription: "Tax/fee rules retrieved successfully",
    querySchema: TaxFeeQueryParamsSchema,
    includeBadRequest: true,
  }),
  getTaxFeeById: createAuthenticatedRoute({
    method: "get",
    path: "/tax-fees/{id}",
    summary: "Get tax/fee by ID",
    description: "Retrieve a tax/fee by ID",
    tags: [ApiTags.TAXES],
    successSchema: TaxFeeResponseSchema,
    successDescription: "Tax/fee retrieved successfully",
    paramsSchema: TaxFeePathParamsSchema,
    includeNotFound: true,
  }),
  createTaxFee: createAuthenticatedRoute({
    method: "post",
    path: "/tax-fees",
    summary: "Create tax/fee",
    description: "Create a tax/fee rule (fixed amounts in paise)",
    tags: [ApiTags.TAXES],
    successSchema: TaxFeeResponseSchema,
    successDescription: "Tax/fee created successfully",
    requestSchema: CreateTaxFeeRequestSchema,
    includeBadRequest: true,
  }),
  updateTaxFee: createAuthenticatedRoute({
    method: "put",
    path: "/tax-fees/{id}",
    summary: "Update tax/fee",
    description: "Update a tax/fee rule",
    tags: [ApiTags.TAXES],
    successSchema: TaxFeeResponseSchema,
    successDescription: "Tax/fee updated successfully",
    paramsSchema: TaxFeePathParamsSchema,
    requestSchema: UpdateTaxFeeRequestSchema,
    includeBadRequest: true,
    includeNotFound: true,
  }),
  deleteTaxFee: createAuthenticatedRoute({
    method: "delete",
    path: "/tax-fees/{id}",
    summary: "Delete tax/fee",
    description: "Delete a tax/fee rule",
    tags: [ApiTags.TAXES],
    successSchema: TaxFeeResponseSchema,
    successDescription: "Tax/fee deleted successfully",
    paramsSchema: TaxFeePathParamsSchema,
    includeNotFound: true,
  }),
};
